using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using System.Numerics;
using Robust.Shared.Prototypes;
using Content.Shared._FarHorizons.Research;
using Robust.Client.ResourceManagement;
using Content.Client._FarHorizons.Research.UI.Helpers;
using System.Linq;

namespace Content.Client._FarHorizons.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FHResearchTree : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<ProtoId<ResearchTreeNodePrototype>?>? OnSelectionChanged;

    private bool _moving = false;
    private Vector2 _viewportPosition = Vector2.Zero;
    private Vector2 _lastViewportPosition = Vector2.Zero;
    private Vector2 _lastMousePos = Vector2.Zero;
    private List<DrawResearchTier> _tiers = [];
    private List<DrawResearchNode> _nodes = [];
    private List<DrawResearchEdge> _edges = [];
    private bool _draw = false;
    private readonly Font _font;

    private ProtoId<ResearchTreeNodePrototype>? _hovered = null;
    private ProtoId<ResearchTreeNodePrototype>? _selected = null;

    private ProtoId<ResearchTreeNodePrototype>? _willSelect = null;

    private HashSet<ProtoId<ResearchTreeTierPrototype>> _unlockedTiers = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _unlockedNodes = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _researched = [];
    private Dictionary<ProtoId<ResearchTreeNodePrototype>, float> _researching = [];

    private Vector2 _currentMousePosition => 
        (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
    

    public int NodeWidth = 100;
    public int NodeHeight = 30;

    public int NodeSpacingHorizontal = 75;
    public int NodeSpacingVertical = 35;

    public int NodeMarginHorizontal = 10;
    public int NodeMarginVertical = 10;

    public string FontPath = "/EngineFonts/NotoSans/NotoSansMono-Regular.ttf";

    public FHResearchTree()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var fontResource = IoCManager.Resolve<IResourceCache>()
                                     .GetResource<FontResource>(FontPath);
        _font = new VectorFont(fontResource, 16);

        DefaultCursorShape = CursorShape.Arrow;
    }

    public void BuildTree(
        HashSet<ResearchTreeNodePrototype> nodes,
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, float> progress
    )
    {   
        var grid = new ResearchTreeGrid(_prototypeManager, nodes);

        (_tiers, _nodes, _edges) = grid.GetDrawable((NodeWidth, NodeHeight), (NodeSpacingHorizontal, NodeSpacingVertical), (NodeMarginHorizontal, NodeMarginVertical), _font);
        _draw = true;
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researched = researched;
        _researching = progress;
    }

    public void RefreshTree(
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, float> progress
    )
    {
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researched = researched;
        _researching = progress;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;
        
        _lastViewportPosition = _viewportPosition;
        if (_nodes.Any(p => p.Proto == _hovered && p.Translate(_viewportPosition).IsHovering(_currentMousePosition)))
        {
            _willSelect = _hovered;
            return;
        }

        DefaultCursorShape = CursorShape.Move;
        _moving = true;
        _lastMousePos = _currentMousePosition;
        UserInterfaceManager.ClickSound();
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        DefaultCursorShape = CursorShape.Arrow;
        _moving = false;
        UserInterfaceManager.ClickSound();

        if (_lastViewportPosition != _viewportPosition)
            return;

        var lastSelection = _selected;
        _selected = _hovered != null && _hovered == _willSelect ? _hovered : null;
        if (lastSelection != _selected)
            OnSelectionChanged?.Invoke(_selected);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_draw)
            return;

        MoveViewport();
        foreach (var tier in _tiers)
            tier
            .Translate(_viewportPosition)
            .DrawBg(handle);
        _hovered = GetHovered();
        foreach (var edge in _edges)
            edge
            .Translate(_viewportPosition)
            .Hovered(_hovered)
            .Research(_researched)
            .Draw(handle);
        for (var i = 0; i < _nodes.Count; i++)
        {
            _nodes[i] = _nodes[i].WrapName(handle); // basically part of initialization, but it requires handle so it's here. Will only run first time
            _nodes[i]
            .Translate(_viewportPosition)
            .Hovered(_currentMousePosition)
            .Select(_selected)
            .Unlock(_unlockedTiers, _unlockedNodes)
            .Research(_researched)
            .Researching(_researching)
            .Draw(handle);
        }
        foreach (var tier in _tiers)
            tier
            .Translate(_viewportPosition)
            .DrawHeader(handle);
    }

    private void MoveViewport()
    {
        if (!_moving)
            return;

        var curMousePos = _currentMousePosition;
        _viewportPosition += _currentMousePosition - _lastMousePos;
        _lastMousePos = curMousePos;
    }

    private ProtoId<ResearchTreeNodePrototype>? GetHovered()
    {
        var hovered = _nodes
        .Where(p => p.Translate(_viewportPosition).IsHovering(_currentMousePosition))
        .Select(p => p.Proto)
        .ToList();

        return hovered.Count > 0 ? hovered.First() : (ProtoId<ResearchTreeNodePrototype>?)null;
    }

    public void Select(ProtoId<ResearchTreeNodePrototype>? select)
    {
        if (_selected != select)
        {
            _selected = select;
            OnSelectionChanged?.Invoke(_selected);
            var node = _nodes.Where(p => p.Proto == _selected).First();
            _viewportPosition = -node.Position + node.Size;
        }
    }
}